ATHENA_HOST="athena"
REMOTE_DIR="/net/tscratch/people/plgbtcaf/zml"
REMOTE_DIRS=(
    "/net/tscratch/people/plgzardori/zml"
    "/net/tscratch/people/plgbtcaf/zml"
    # "/net/pr2/projects/plgrid/plggtriplane/poblos/zml"
)
