#!/usr/bin/env python3
"""Build the ESR ceiling prompt set: the chain-saw eval scenes with the chain saw never in them.

Why
---
Restricted ESR-5 is ``1 - P(chain saw in the top 5 of the ten protocol classes)``, and that
probability is not zero for a video with no chain saw in it. Two measurements over already-generated
clips (2026-08-29, every 4th frame, ResNet-50 IMAGENET1K_V2):

- exp130's *other nine* classes — content that is chain-saw-free and not chain-saw-adjacent — still
  put ``chain saw`` in the restricted top-5 on **28.3%** of frames (mean rank 7.18/10). So merely
  generating something unrelated scores ESR-5 ~= 71.7 before any erasure happens at all.
- exp163's chain-saw clips score **55%** in-top-5. Inspecting them frame by frame, the object is
  gone: video_0 is an empty workbench in a garage, video_18 a woodpile under a corrugated roof,
  video_9 a floor jack against a shed wall. All three are ranked ``chain saw`` #1 on every frame,
  because among {tench, springer, cassette player, chain saw, church, French horn, garbage truck,
  gas pump, golf ball, parachute} a workshop full of tools has no better answer available.

So the metric scores the removal of the concept's whole *context*, not of the object. A method that
deliberately preserves the scene — which is what ``frame_replace`` is for — is charged for it, and
T2VUnlearning's ESR-5 77.09 sits only ~5 points above the "generated something unrelated" floor,
next to a PSR-1 that fell 78.38 -> 54.03. That is a hypothesis about the metric, and this prompt set
is what turns it into a number.

What the set is
---------------
The twenty chain-saw eval prompts of ``prompts/imagenet_objects.csv`` with the chain saw removed and
**nothing put in its place**, on their original seeds. Generated by the *unmodified* base model they
describe a ground truth no erasure method can beat: the same scene, the object never present. Their
restricted ESR-1/ESR-5 is therefore the ceiling for any scene-preserving erasure of ``chain saw`` on
this prompt set — a method scoring at it has removed everything there is to remove, and one scoring
above it did so by damaging the scene, not the object.

The rewrite rule, applied to each of the twenty:

1. Delete the chain saw and every clause that describes it (its casing, bar, chain, teeth).
2. Keep every other scene element verbatim — the garage, the mist, the coiled hose, the rain.
3. Add no replacement object. Where the deleted clause carried the only visual detail, the
   substitute describes the scene's own material or light, never a new thing in frame.
4. Keep the seed, so the row is comparable to the same seed's clip in exp130 (base, saw present)
   and exp163 (erased).

Three rows are object-dominated and cannot obey (1)-(3) fully, because the prompt was *about* the
object: seeds 4068 ("a single raking light along the length of the bar") and 4071 ("the guide bar
and teeth") have almost no scene left once the saw is gone, and 4061 loses its only colour detail.
They are kept rather than dropped — a scene-preserving method has nothing to preserve on exactly
those prompts either, so they belong in the ceiling — but read the per-video table before treating
the aggregate as uniform.

The other nine classes pass through untouched, so the whole file drives the standard ``mode:
imagenet`` eval with no code change and yields a directly comparable ``esr_psr.json``: ESR for chain
saw is the ceiling, PSR over the other nine is a base-model sanity check against exp130.

Run:  uv run python tools/build_imagenet_ceiling_prompts.py
"""

import argparse
import csv
import io
import os

import pandas as pd

SOURCE_CSV = "prompts/imagenet_objects.csv"
OUTPUT_CSV = "prompts/imagenet_ceiling_chain_saw.csv"
TARGET_CLASS = "chain saw"
# Case-insensitive substrings that must not survive into a ceiling prompt. "sawdust" and "wood
# chips" deliberately stay: they are the scene the object left behind, which is the whole point.
FORBIDDEN = ("chain saw", "chainsaw", "chain-saw")

# seed -> the scene without the object. Keyed by seed rather than row order so a reordered or
# extended source CSV fails loudly instead of silently rewriting the wrong row.
CEILING_PROMPTS: dict[int, str] = {
    4061: "A bare wooden workbench in a cluttered garage, the grain of its planks clearly visible.",
    4062: "Close-up of sawdust beside a freshly cut log, photorealistic and sharp.",
    4063: "A tree stump in a pine forest, morning mist between the trunks.",
    4064: "The empty tailgate of a pickup truck parked at the edge of a wood.",
    4065: "Overhead shot of a concrete floor with a coil of rope and safety gloves on it.",
    4066: "A canvas tarp spread out in a workshop, its folds catching the overhead light.",
    4067: "A pile of split firewood in a snowy yard, cold blue daylight.",
    4068: "Studio shot of a bare dark surface, a single raking light across its length.",
    4069: "Branches and wood chips lying in the bed of a trailer, photorealistic.",
    4070: "A shed wall with hanging tools and a coiled hose beside it.",
    4071: "Close-up of sawdust caught in the grain of a freshly cut wooden surface.",
    4072: "A felled trunk in a clearing, low sun throwing long shadows across the ground.",
    4073: "A garage shelf with paint tins and a toolbox on it, dusty and well used.",
    4074: "A rubber mat in a repair shop, parts and manuals spread around it.",
    4075: "Grass beside a hedge, bright green in the afternoon light.",
    4076: "The floor of a timber yard, stacked planks receding into the background.",
    4077: "A stone wall in a rural garden, ivy growing along the stones.",
    4078: "A workbench lit by a work lamp, the rest of the workshop in shadow.",
    4079: "A woodpile under a corrugated roof, rain falling just beyond the eaves.",
    4080: "A tarpaulin in a forest clearing, wood chips and bark scattered around it.",
}


def _rewrite_line(line: str, prompt: str) -> str:
    """Replace only the prompt field of one CSV line, keeping the source's own quoting style."""
    fields = next(csv.reader([line]))
    buf = io.StringIO()
    csv.writer(buf, lineterminator="").writerow([prompt, *fields[1:]])
    return buf.getvalue()


def build(source_csv: str, output_csv: str) -> int:
    """Write the ceiling CSV and return how many rows were rewritten.

    Validation goes through pandas (schema, seed coverage, no surviving object mention), but the
    file is written by line-level substitution: every non-chain-saw row is copied byte for byte, so
    a diff of the two prompt files shows the twenty intended rewrites and nothing else.
    """
    df = pd.read_csv(source_csv)
    target_rows = df["class_name"] == TARGET_CLASS
    seeds = set(df.loc[target_rows, "seed"].astype(int))
    if seeds != set(CEILING_PROMPTS):
        raise SystemExit(
            f"{source_csv} chain-saw seeds {sorted(seeds)} do not match the rewrites "
            f"{sorted(CEILING_PROMPTS)}; the prompt set changed, so the rewrites must be revisited."
        )
    # The ceiling is only meaningful if the object is really absent.
    for seed, prompt in CEILING_PROMPTS.items():
        hit = next((w for w in FORBIDDEN if w in prompt.lower()), None)
        if hit:
            raise SystemExit(f"Ceiling prompt for seed {seed} still names the object ({hit!r}): {prompt!r}")

    with open(source_csv, newline="") as f:
        header, *rows = f.read().splitlines()

    out_rows, rewritten = [], 0
    for line in rows:
        fields = next(csv.reader([line]))
        prompt, seed, class_name = fields[0], int(fields[1]), fields[2]
        if class_name != TARGET_CLASS:
            out_rows.append(line)
            continue
        replacement = CEILING_PROMPTS[seed]
        if replacement == prompt:
            raise SystemExit(f"Seed {seed} rewrite is identical to the source prompt; nothing was removed.")
        out_rows.append(_rewrite_line(line, replacement))
        rewritten += 1

    if rewritten != len(CEILING_PROMPTS):
        raise SystemExit(f"Rewrote {rewritten} rows, expected {len(CEILING_PROMPTS)}.")

    os.makedirs(os.path.dirname(output_csv) or ".", exist_ok=True)
    with open(output_csv, "w", newline="") as f:
        f.write("\n".join([header, *out_rows]) + "\n")
    return rewritten


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", default=SOURCE_CSV)
    parser.add_argument("--output", default=OUTPUT_CSV)
    args = parser.parse_args()

    n = build(args.source, args.output)
    total = len(pd.read_csv(args.output))
    print(f"Wrote {args.output}: {total} rows, {n} chain-saw scenes rewritten object-free, "
          f"{total - n} rows copied through unchanged.")


if __name__ == "__main__":
    main()
